// Exemplos preenchidos de cada mensagem do WhatsApp (nomes, números e horários de mentira):
// a revisão de textos (scripts/gerar-revisao-textos.ts) e a prévia das mensagens automáticas no
// painel (0570) usam os mesmos.
import type { Modelo, ParametrosMensagem } from "./mensagens.ts";
import type { Promocao } from "./preco.ts";

// Horários de exemplo no fuso da loja (UTC-3): 17:32 UTC = 14:32
const h = (hhmm: string) => new Date(`2026-10-10T${String(Number(hhmm.slice(0, 2)) + 3).padStart(2, "0")}:${hhmm.slice(3)}:00Z`);
const periodo = { inicio: new Date("2026-09-01T00:00:00Z"), fim: new Date("2026-12-31T00:00:00Z") };
const promocoes: Promocao[] = [
  { ...periodo, id: "p1", nome: "Club", tipo: "COMPRE_MAIS", modo: "PRECO_POR_GRUPO", escopo: "TODOS", produtos: [], umaPorCliente: false, grupo: { qtd: 3, precoCentavos: 11999 } },
  { ...periodo, id: "p2", nome: "Boas-vindas VIP", tipo: "CUPOM", escopo: "TODOS", produtos: [], codigo: "VIP5", modo: "PERCENTUAL", valor: 5,
    quantidadeTotal: 1000, quantidadeUsada: 0, limitePorCliente: 1, validadeDias: 30 },
];

export type ExemploMensagem = { [M in Modelo]: { modelo: M; titulo: string; p: ParametrosMensagem[M] } }[Modelo];
export const EXEMPLOS_MENSAGENS: ExemploMensagem[] = [
  { modelo: "codigo_verificacao", titulo: "Código de verificação", p: { codigo: "482193", minutos: 5 } },
  { modelo: "numero_diferente", titulo: "Pedido de código de outro número", p: {} },
  { modelo: "sem_numero", titulo: "WhatsApp não mostrou o número (LID)", p: {} },
  { modelo: "referencia_invalida", titulo: "Pedido de código com referência errada", p: {} },
  { modelo: "codigo_bloqueado", titulo: "Muitas tentativas de código", p: { ate: h("14:47") } },
  { modelo: "reserva_criada", titulo: "Reserva criada: 1 peça", p: { nome: "Ana Paula", pecas: 1, numero: 1048, totalCentavos: 4999, expiraEm: h("14:47"), link: "https://tshirtclub.vercel.app/r#…" } },
  { modelo: "reserva_criada", titulo: "Reserva criada: 2 peças, falta 1 para o Club", p: { nome: "Ana Paula", pecas: 2, numero: 1048, totalCentavos: 9998, expiraEm: h("14:47"), link: "https://tshirtclub.vercel.app/r#…", grupo: { qtd: 3, precoCentavos: 11999 } } },
  { modelo: "reserva_criada", titulo: "Reserva criada: 3 peças (Club)", p: { nome: "Ana Paula", pecas: 3, numero: 1048, totalCentavos: 11999, expiraEm: h("14:47"), link: "https://tshirtclub.vercel.app/r#…" } },
  { modelo: "reserva_lembrete_5min", titulo: "Lembrete de 5 minutos", p: { numero: 1048, expiraEm: h("14:47"), nome: "Ana Paula", pecas: 3 } },
  { modelo: "reserva_expirada", titulo: "Reserva expirada, com as peças que ainda estão à venda (a Clubinha recupera a venda)", p: { numero: 1048, expiradaEm: h("14:47"), nome: "Ana Paula",
    disponiveis: [{ nome: "Limone Amalfi", slug: "limone-amalfi" }, { nome: "Estate Roma (Plus)", slug: "estate-roma" }] } },
  { modelo: "reserva_expirada", titulo: "Reserva expirada, com as peças já vendidas", p: { numero: 1048, expiradaEm: h("14:47"), nome: "Ana Paula", disponiveis: [] } },
  { modelo: "reserva_expirada", titulo: "Reserva expirada que bloqueou o número (sem convite)", p: { numero: 1048, expiradaEm: h("14:47"), pausada: true } },
  { modelo: "pagamento_confirmado", titulo: "Pagamento confirmado", p: { nome: "Ana Paula", numero: 1048, totalCentavos: 11999, forma: "PIX", pecas: 3 } },
  { modelo: "pagamento_em_analise", titulo: "Pagamento em análise: depois do prazo", p: { numero: 1048 } },
  { modelo: "pagamento_em_analise", titulo: "Pagamento em análise: valor diferente", p: { numero: 1048, valorDivergente: true } },
  { modelo: "pagamento_em_analise", titulo: "Pagamento em análise: frete", p: { numero: 1048, frete: true } },
  { modelo: "telefone_bloqueado", titulo: "Telefone bloqueado", p: {} },
  { modelo: "telefone_liberado", titulo: "Telefone liberado", p: {} },
  { modelo: "bloqueio_mantido", titulo: "Bloqueio mantido", p: {} },
  { modelo: "cancelamento_recebido", titulo: "Cancelamento recebido", p: { numero: 1048, expiraEm: h("14:47") } },
  { modelo: "cancelamento_aprovado", titulo: "Cancelamento aprovado", p: { numero: 1048 } },
  { modelo: "reserva_cancelada", titulo: "Cancelada pela loja: reserva não paga", p: { numero: 1048, nome: "Ana", pago: false } },
  { modelo: "reserva_cancelada", titulo: "Cancelada pela loja: pedido pago, com estorno no PIX", p: { numero: 1048, nome: "Ana", pago: true, estornoCentavos: 11999, forma: "PIX" } },
  { modelo: "reserva_cancelada", titulo: "Cancelada pela loja: pedido pago, com estorno no cartão", p: { numero: 1048, nome: "Ana", pago: true, estornoCentavos: 11999, forma: "CARTAO" } },
  { modelo: "reserva_cancelada", titulo: "Cancelada pela loja: venda paga fora do site", p: { numero: 1048, nome: "Ana", pago: true, porFora: true } },
  { modelo: "cancelamento_recusado", titulo: "Cancelamento recusado", p: { numero: 1048, expiraEm: h("14:47") } },
  { modelo: "entrega_confirmada", titulo: "Entrega escolhida: retirada", p: { numero: 1048, modalidade: "RETIRADA" } },
  { modelo: "entrega_confirmada", titulo: "Entrega escolhida: motoboy ou envio", p: { numero: 1048, modalidade: "MOTOBOY" } },
  { modelo: "entrega_confirmada", titulo: "Endereço corrigido pela loja", p: { numero: 1048, modalidade: "MOTOBOY", alterado: true } },
  { modelo: "frete_calculado", titulo: "Frete calculado", p: { numero: 1048, valorCentavos: 1500, pagarAte: h("16:32") } },
  { modelo: "frete_confirmado", titulo: "Frete pago", p: { numero: 1048 } },
  { modelo: "pronto_retirada", titulo: "Pronto para retirada", p: { numero: 1048, codigo: "K7Q2", endereco: "R. Sátiro Santos, 38 - Caetité, BA, 46400-000", horario: "Aberto 24 horas, com retirada agendada: responda esta mensagem para combinar o horário." } },
  { modelo: "saiu_entrega", titulo: "Saiu para entrega", p: { numero: 1048 } },
  { modelo: "pedido_enviado", titulo: "Pedido enviado (com rastreio)", p: { numero: 1048, rastreio: "QB123456789BR" } },
  { modelo: "pedido_entregue", titulo: "Pedido entregue", p: { numero: 1048, nome: "Ana Paula" } },
  { modelo: "minhas_reservas", titulo: "Resposta a \"Minha reserva\": com reservas", p: { reservas: [
    { numero: 1048, status: "RESERVADO", pecas: 3, totalCentavos: 11999, expiraEm: h("14:47") },
    { numero: 1031, status: "PAGAMENTO_CONFIRMADO", totalCentavos: 4999, substatus: "PRONTO_PARA_RETIRADA" },
    { numero: 1012, status: "EXPIRADO", motivoEncerramento: "PRAZO_ESGOTADO", totalCentavos: 9998 },
  ] } },
  { modelo: "minhas_reservas", titulo: "Resposta a \"Minha reserva\": sem reservas", p: { reservas: [] } },
  { modelo: "ofertas", titulo: "Resposta a \"ofertas\"", p: { promocoes } },
  { modelo: "ofertas", titulo: "Resposta a \"ofertas\": sem ofertas", p: { promocoes: [] } },
  { modelo: "trocas", titulo: "Resposta sobre trocas", p: {} },
  { modelo: "boas_vindas", titulo: "Resposta automática (mensagem comum), com o menu", p: { opcoes: [
    { numero: 1, titulo: "Ver as peças e reservar" }, { numero: 2, titulo: "Tamanhos e medidas" }, { numero: 3, titulo: "Entrega e frete" },
    { numero: 4, titulo: "Pagamento" }, { numero: 5, titulo: "Horário e endereço" }, { numero: 6, titulo: "Minha reserva" },
    { numero: 7, titulo: "Ofertas e cupons" }, { numero: 8, titulo: "Trocas e devoluções" }, { numero: 9, titulo: "Falar com a equipe" },
  ] } },
  { modelo: "boas_vindas", titulo: "Resposta automática para quem já reservou: pelo nome e com a coleção mais nova", p: { nome: "Ana Paula", novidade: { nome: "Estate Italiana", slug: "estate-italiana" },
    opcoes: [{ numero: 1, titulo: "Ver as peças e reservar" }, { numero: 2, titulo: "Tamanhos e medidas" }, { numero: 3, titulo: "Falar com a equipe" }] } },
  { modelo: "boas_vindas", titulo: "Resposta automática (mensagem comum), com as respostas rápidas desligadas", p: {} },
  { modelo: "resposta_rapida", titulo: "Resposta rápida (o texto vem do painel, com a volta para o menu)", p: { texto: "É tudo pelo site, com o Mercado Pago:\n• *PIX*, confirmado na hora\n• *Cartão de crédito*\n\nDepois de reservar, o link para pagar chega aqui no WhatsApp ✦" } },
  { modelo: "atendimento_lembrete", titulo: "Acompanhamento: a cliente pediu a equipe e ninguém respondeu em 20 minutos", p: { nome: "Ana Paula" } },
  { modelo: "pos_venda", titulo: "Acompanhamento: 2 dias depois da entrega ou retirada", p: { nome: "Ana Paula", pecas: 3 } },
  { modelo: "chamado_aberto", titulo: "Chamado: a dúvida que a Clubinha não soube responder passa para a equipe", p: {} },
  { modelo: "atendimento_encerrado", titulo: "Chamado finalizado pela equipe: agradecimento e pedido de nota", p: { nome: "Ana Paula" } },
  { modelo: "avaliacao_recebida", titulo: "Nota 4 ou 5", p: { nota: 5, menu: true } },
  { modelo: "avaliacao_recebida", titulo: "Nota de 1 a 3", p: { nota: 2, menu: true } },
  { modelo: "chamado_equipe", titulo: "Para a equipe: depois de \"assumi 12\"", p: { resultado: "ASSUMIDO", numero: 12, nome: "Ana" } },
  { modelo: "chamado_equipe", titulo: "Para a equipe: depois de \"resolvido 12\"", p: { resultado: "RESOLVIDO", numero: 12, nome: "Ana", notaPedida: true } },
  { modelo: "chamado_equipe", titulo: "Para a equipe: número de chamado errado", p: { resultado: "NAO_ENCONTRADO", numero: 99 } },
  { modelo: "aviso_loja", titulo: "Aviso para a equipe: chamado de dúvida que a Clubinha não respondeu", p: { tipo: "atendimento", chamado: 12, motivo: "DUVIDA", nome: "Ana",
    telefone: "+5577998128809", pedido: { numero: 1048, status: "RESERVADO" }, mensagens: ["Vocês fazem embrulho pra presente?"] } },
  { modelo: "aviso_loja", titulo: "Aviso para a equipe: cliente quer falar com a equipe", p: { tipo: "atendimento", chamado: 12, motivo: "EQUIPE", nome: "Ana", telefone: "+5577998128809",
    pedido: { numero: 1048, status: "RESERVADO" }, mensagens: ["Oi, boa tarde", "Tem a Limone Capri no Plus?"] } },
  { modelo: "aviso_loja", titulo: "Aviso para a equipe: ninguém assumiu o chamado em 20 minutos", p: { tipo: "atendimento", chamado: 12, lembrete: true, desde: h("14:12"), nome: "Ana",
    telefone: "+5577998128809", pedido: { numero: 1048, status: "RESERVADO" }, mensagens: ["Tem a Limone Capri no Plus?"] } },
  { modelo: "aviso_loja", titulo: "Aviso para a equipe: cliente falou em troca", p: { tipo: "troca", chamado: 13, motivo: "TROCA", nome: "Ana", telefone: "+5577998128809",
    pedido: { numero: 1031, status: "ENTREGUE" }, mensagens: ["Quero trocar a camiseta, ficou grande"] } },
  { modelo: "aviso_loja", titulo: "Aviso para a equipe: nota do atendimento", p: { tipo: "avaliacao", chamado: 12, nome: "Ana", nota: 5 } },
  { modelo: "mensagem_teste", titulo: "Mensagem de teste do painel", p: {} },
];
